import create from "zustand";

export const useGlobal = create((set) => ({
  selectedCategory: "",
  handleSelectedCategory: (newCategory) =>
    set({ selectedCategory: newCategory }),
  items: [
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",
      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      commision: 100,
      safe: 30,
      havala_date: "2022-03-07",
    },
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",

      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",

      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },

    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",

      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",

      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",

      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",

      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",

      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },
    {
      id: "49384934",
      havala_type: "کارت به کارت",
      number_havala: "1001",
      fullName: "رضا حبیبی",
      from_city: "هامبورگ",
      to_city: "کابل",
      purchased_price: 98,
      sell_price: 102,
      havala_amount: 500,
      // safe: ((sell_price - purchased_price) * havala_amount) / purchased_price,
      safe: 30,
      havala_date: "2022-03-07",
    },
  ],
  handleItems: (newItem) => set({ items: [...newItem] }),
}));
