import "../../Styles/StaticComponents/Table.css"
export function Table() {
    return(
        <div className="table-container">
            <table>
                <thead>
                    <tr>
                        <th>ردیف</th>
                        <th>نوعیت</th>
                        <th>نام</th>
                        <th>کمپنی</th>
                        <th>کشور</th>
                        <th>تعداد</th>
                        <th>قیمت</th>
                        <th>جمع</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>کپسول</td>
                        <td>آموکسی500</td>
                        <td>فارابی</td>
                        <td>ایرانی</td>
                        <td>1000</td>
                        <td>350</td>
                        <td>350000</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>45524354363</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    )
}